events { worker_connections 1024; }
http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on; gzip on;
    server {
        listen 80;
        root /usr/share/nginx/html;
        index pages/login.html;
        location / { try_files \ \/ /pages/login.html; }
        location /api/ {
            proxy_pass http://backend:5000;
            proxy_set_header Host \System.Management.Automation.Internal.Host.InternalHost;
            proxy_set_header X-Real-IP \;
        }
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
    }
}
